ifb299_website/ifb299_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
]

urlpatterns += staticfiles_urlpatterns()

ifb299_website/search/urls.py
from django.urls import path
from . import views

app_name = 'search'
urlpatterns = [
    path('', views.home, name='home'),
    path('details/<int:id>/', views.car_detail, name='car_detail'), # Passes parameter <int:id> (car.car_id) to dynamically create details page
    path('about/', views.about, name='about'),
    path('search/', views.about, name='search'),
    path('locations/', views.locations, name='locations'),
]

ifb299_website/search/models.py
from django.db import models
from django.core.validators import RegexValidator

# Regex Validator to validate four digit year fields
year_validator = RegexValidator(
    regex='[0-9]{4}',
    message='Year must be a four digit number',
    code='Invalid year'
)

# Represents a Car and its fields in the database
class Car(models.Model):
    car_id = models.IntegerField(primary_key=True, default=0)
    car_make = models.CharField(max_length=50)
    car_model = models.CharField(max_length=50)
    car_series = models.CharField(max_length=50)
    car_series_year = models.CharField(max_length=4, validators=[year_validator])
    car_price_new = models.IntegerField()
    car_engine_size = models.CharField(max_length=50)
    car_fuel_system = models.CharField(max_length=50)
    car_tank_capacity = models.CharField(max_length=50)
    car_power = models.CharField(max_length=50)
    car_seating_capacity = models.IntegerField()
    car_standard_transmission = models.CharField(max_length=50)
    car_body_type = models.CharField(max_length=50)
    car_drive = models.CharField(max_length=50)
    car_wheelbase = models.CharField(max_length=50)
    def __str__(self):
        return self.car_make + ' ' + self.car_model

# Represents a Customer and its fields in the database
class Customer(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female')
    )
    customer_id = models.IntegerField(primary_key=True, default=0)
    customer_name = models.CharField(max_length=50)
    customer_phone = models.CharField(max_length=50)
    customer_address = models.CharField(max_length=50)
    customer_birthday = models.CharField(max_length=50)
    customer_occupation = models.CharField(max_length=50)
    customer_gender = models.CharField(max_length = 6, choices=GENDER_CHOICES)
    def __str__(self):
        return self.customer_name

# Represents a Store and its fields in the database
class Store(models.Model):
    store_id = models.IntegerField(primary_key=True, default=0)
    store_name = models.CharField(max_length=50)
    store_address = models.CharField(max_length=50)
    store_phone = models.CharField(max_length=50)
    store_city = models.CharField(max_length=50)
    store_state = models.CharField(max_length=50)
    def __str__(self):
        return self.store_name

# Represents an ORder and its fields in the database
class Order(models.Model):
    order_id = models.IntegerField(primary_key=True, default=0)
    order_create_date = models.CharField(max_length=50)
    order_pickup_date = models.CharField(max_length=50)
    order_pickup_store = models.IntegerField()
    pickup_store_name = models.CharField(max_length=50)
    pickup_store_address = models.CharField(max_length=50)
    pickup_store_phone = models.CharField(max_length=50)
    pickup_store_city = models.CharField(max_length=50)
    pickup_store_state = models.CharField(max_length=50)
    order_return_date = models.CharField(max_length=50)
    order_return_store = models.IntegerField()
    return_store_name = models.CharField(max_length=50)
    return_store_address = models.CharField(max_length=50)
    return_store_phone = models.CharField(max_length=50)
    return_store_city = models.CharField(max_length=50)
    return_store_state = models.CharField(max_length=50)

ifb299_website/search/forms.py
from django import forms
from django.core.exceptions import ValidationError

year_choices = [('Blank', '')]
sort_choices = [('ASC', 'Price Ascending'), ('DESC', 'Price Descending')]
# Simple loop to populate year_choices for the 'year' field in SearchForm
for x in range(1900,2020,10):
    year_choices.append((x,x))

# Form that takes user input to search the database for Cars
class SearchForm(forms.Form):
	query = forms.CharField(label='Search', max_length=100, required=False)
	min_price = forms.IntegerField(label='Min Price', min_value=0, max_value=9999999, required=False)
	max_price = forms.IntegerField(label='Max Price', min_value=0, max_value=9999999, required=False)
	year = forms.ChoiceField(label='Year', choices=year_choices, required=False)
	sort = forms.ChoiceField(label='Sort', choices=sort_choices, required=False)

ifb299_website/search/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.db.models import Q
from .models import Car, Store
from .forms import SearchForm
from django.shortcuts import render


# View to handle homepage requests
def home(request):
    title = "Home"
    form = SearchForm(request.GET) # Create bound SearchForm with form data submitted in GET request
    max_items = 21
    # If all form fields are valid, clean the data and begin filtering
    if form.is_valid():
        car_query_list = Car.objects.all()
        query = form.cleaned_data['query']
        min_price = form.cleaned_data['min_price']
        max_price = form.cleaned_data['max_price']
        year = form.cleaned_data['year']
        sort = form.cleaned_data['sort']
        # Check for empty fields and set defaults if necessary
        if not min_price:
            min_price = 0
        if not max_price:
            max_price = 9999999
        car_query_list = car_query_list.filter(car_price_new__range=(min_price, max_price))
        if not query == None:
            car_query_list = car_query_list.filter(Q(car_make__icontains=query) | Q(car_model__icontains=query) | Q(car_series__icontains=query) | Q(car_body_type__icontains=query))
        if year != 'Blank':
            year_max = 0
            if year.isdigit():
                year_max = int(year) + 9
            car_query_list = car_query_list.filter(car_series_year__range=(year, year_max))
        if sort == 'ASC':
            car_query_list = car_query_list.order_by('car_price_new')
        if sort == 'DESC':
            car_query_list = car_query_list.order_by('-car_price_new')
    # Create unbound SearchForm if form is not valid or is not submitted
    else:
            car_query_list = None
            form = SearchForm()
    context = {
        'title': title,
        'form' : form,
        'car_query_list' : car_query_list[0:max_items]
    }
    return render(request, 'search/home.html', context)

# View to handle car detail requests
def car_detail(request, id):
    # Get car based on its ID or return 404
    selected_car = get_object_or_404(Car, pk=id)
    context = {
        'selected_car' : selected_car
    }
    return render(request, 'search/detail.html', context)

# View to handle About Us page requests
def about(request):
    about = "About Us"
    context = {
        'title': about
        }
    return render(request, 'search/about.html', context)

# View to handle Locations page requests
def locations(request):
    title = "Locations"
    storeList = Store.objects.all()
    context = {
        'title': title,
        'storeList': storeList
        }
    return render(request, 'search/locations.html', context)

ifb299_website/search/templates/search/about.html
{% extends "search/base.html" %}
{% load static %}
{% block content %}


<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->



<title>About Us</title>
<head/>

<div style="width: 700px; margin-left: auto; margin-right: auto; background: #F0F8FF;" >
  <h2 margin = center>About Us<h2/>
      <font size = "3" style="font-family: Arial; margin-left: 1em; background: #F0F8FF; ">
      <p>We strive to make renting a car as simple and easy as driving your own car.</br></br>

        Renting a car brings you freedom and we want to help you find the right car for you at the right price.
        We have locations all over Australia and offer a wide range of vehicles that will suit each customers
        needs and preferences. </br></br>

        We offer a range of features to make be sure you can find the right car for you:
        <p/>

          <ul style="margin-left: 2em; list-style-type:circle; list-style-image: url('https://d2ztnewirs5p02.cloudfront.net/categories/common/page-icons/ic_car-201712121112.png')"><li><b>Search:</b> You can search the site for the car you want</li>
          <li><b>Tailor your search:</b> You can filter your results based on a criteria of your choosing</li>
          <li><b>View detailed car info: </b> You can view information in detail of all of our cars</li>
          <li><b>Location info: </b> You can view the locations of all our stores and the cars available at which locations using a Google Maps functionality</li>
          <li><b>Recommendations: </b> You can view what cars other customers have recommended
            and see a rating of their experiences with a car, this can help you choose the right car for you.
            You can also leave a rating of your experience with a car to help future customers</li>

        </ul>
      </font>

<img src='https://carsirent.com/blog/wp-content/uploads/2017/10/car-rental-stock.jpg' width="700" height="300"></img>
</div>

{% endblock content%}

ifb299_website/search/templates/search/about_us.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">


<title>About Us</title>
<head/>
<body style="background:  #F0F8FF">

<div style="width: 700px; margin-left: auto; margin-right: auto" >
  <h2 margin = center >About Us<h2/>
      <font size = "3" style="margin-left: 1em;">
      <p>We strive to make renting a car as simple and easy as driving your own car.</br></br>

        Renting a car brings you freedom and we want to help you find the right car for you at the right price.
        We have locations all over Australia and offer a wide range of vehicles that will suit each customers
        needs and preferences. </br></br>

        We offer a range of features to make sure you can find the right car for you:
        <p/>

          <ul style="list-style-type:circle; list-style-image: url('https://d2ztnewirs5p02.cloudfront.net/categories/common/page-icons/ic_car-201712121112.png')"><li><b>Search:</b> You can search the site for the car you want</li>
          <li><b>Tailor your search:</b> You can filter your results based on a criteria of your choosing</li>
          <li><b>View detailed car info: </b> You can view information in detail of all of our cars</li>
          <li><b>Location info: </b> You can view the locations of all our stores and the cars available at which locations using a Google Maps functionality</li>
          <li><b>Recommendations: </b> You can view what cars other customers have recommended
            and see a rating of their experiences with a car, this can help you choose the right car for you.
            You can also leave a rating of your experience with a car to help future customers</li>

        </ul>
      </font>

<img src='https://carsirent.com/blog/wp-content/uploads/2017/10/car-rental-stock.jpg' width="700" height="300"></img>
</div>
<div>

</div>
</body>
</html>

ifb299_website/search/templates/search/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static '/main.css' %}">
  <!-- Changes title of open tab -->
	{% if title %}
		<title>{{ title }}</title>
	{% else %}
		<title> Car Rentals</title>
	{% endif %}
  </head>
  <!-- Puts up image on the homepage -->
  <body style="background:  #F0F8FF;">
  {% if title == "Home" %}
        <img src="{% static 'car_banner.jpg' %}" alt="Cars" style="border:1px solid black; display: block; margin-right: auto; margin-left: auto;" width="90%" height="100%"></img>
      {% endif %}
      <!-- Creates navigation bar -->
	<header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'search:home' %}">Car Rentals</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'search:home' %}">Home</a>
			  <a class="nav-item nav-link" href="{% url 'search:locations' %}">Locations</a>
			  <a class="nav-item nav-link" href="{% url 'search:about' %}">About Us</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{% url 'admin:index' %}">Login</a>
            </div>
          </div>
        </div>
      </nav>

    </header>

	<div class="container" style="background: #F0F8FF">
		{% block content %}{% endblock %}
	</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

ifb299_website/search/templates/search/detail.html
{% extends "search/base.html" %}
{% load static %}
{% block content %}
{% if selected_car %}
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <style type="text/css">
    * {box-sizing: border-box;}
.mySlides {display: none;}
img {vertical-align: right;}

/* Slideshow container */
.slideshow-container {
  max-width: 1000px;
  position: relative;
  margin-left: 150px;
  margin-top: 20px;
}


/* Caption text */
.text {
  color: #f2f2f2;
  font-size: 15px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
}



/* The dots/bullets/indicators */
.dot {
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.6s ease;
}

.active {
  background-color: #717171;
  
}

/* Fading animation */
.fade {
  -webkit-animation-name: fade;
  -webkit-animation-duration: 10s;
  animation-name: fade;
  animation-duration: 10s;
}

@-webkit-keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

@keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}



ul {    
    padding: 20px;
  margin-top: 5px;
}

ul li {
    margin-left: 10px;
}

* {
    box-sizing: border-box;
}

/* Create two unequal columns that floats next to each other */
.column {
    float: left;
    padding: 10px;
}

.left {
  width: 69%;
  box-shadow: 0px 0px 5px darkblue;
  height: 300px;
  border-radius: 10px;
  
}

.right {
  width: 30%;
  box-shadow: 0px 0px 5px darkblue;
  margin-left: 3px;
  height: 350px;
  border-radius: 10px;
  
}

/* Clear floats after the columns */
.row:after {
    content: "";
    display: table;
    clear: both;
}


h2 {
    color: white;
    text-shadow: 1px 1px 2px #000000;
  background-color: black;
  border-radius: 10px;
  box-shadow: 0px 0px 5px darkblue ;
}

img {
  border-radius: 3%;
}

.button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 16px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 20px 500px;
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
    cursor: pointer;
}

.button1 {
    background-color: #5D8AA8; 
    color: white; 
    border: 2px solid #F0F8FF;
  border-radius: 10%;
}



.button1:hover {
    background-color: #F0F8FF;
    color: black;
  border: 2px solid #5D8AA8;
  border-radius: 10%;
}

.cell {
  width: 32%; 
  margin-right: 
  calc(53%); 
  border-collapse: 
  collapse; 
  border-color: #8b8989; 
  background: #f5f5f5; 
  margin-top: 1em;
}

.center {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 50%;
}


.header-image {
  width: 98%;
  height: 100%;
}


.search {
  background: #60e7f5;
  color: #ffffff;
  border: 1px solid #ffffff;
  width: 60%;
  height: 120px;
}
  </style>
  </head>
  
<body>

<!-- Creates image slideshow -->
<div class="slideshow-container">

<div class="mySlides fade">
  <img src="https://cnet4.cbsistatic.com/img/Dmyt0Djazt7vHsplr6BKpuABxaI=/1600x900/2017/12/04/4cc1c00e-7801-47d9-83f7-ec896d9a8383/lamborghini-urus-3-4-front.jpg" style="width:950px;height:560px;">
</div>

<div class="mySlides fade">
  <img src="https://st.motortrend.com/uploads/sites/5/2018/04/2019-Lamborghini-Urus-in-Rome-3.jpg" style="width:950px;height:560px;">
</div>

<div class="mySlides fade">
  <img src="https://cdn.vox-cdn.com/thumbor/Rh7ZBRId0_4CuKGHqkJbs1GQBZY=/0x0:3000x1605/1200x800/filters:focal(1005x510:1485x990)/cdn.vox-cdn.com/uploads/chorus_image/image/57854899/493264.0.jpg" style="width:950px;height:560px;">
</div>

</div>
<br>

<div style="text-align:center">
  <span class="dot"></span> 
  <span class="dot"></span> 
  <span class="dot"></span> 
</div>



<h2 style="text-align:center;" >{{selected_car.car_make}} {{selected_car.car_model}} {{selected_car.car_series}}</h2>

<div class="row">
  <div class="column left" style="background-color:#F0F8FF;">
    <h3>Description</h3>
   <p>The {{selected_car.car_make}} {{selected_car.car_model}} {{selected_car.car_series}} is manufactured by the car manufacturer {{selected_car.car_make}}.

   </p>
  </div>
  
  <div class="column right" style="background-color:#F0F8FF;">
  <!-- details Specifications box -->
    <h3>Specifications</h3>
    <ul>
    <li>Body type: {{selected_car.car_body_type}}</li>
    <li>Engine size: {{selected_car.car_engine_size}}</li>
    <li>Fuel Capacity: {{selected_car.car_tank_capacity}}</li>
    <li>Fuel system: {{selected_car.car_fuel_system}}</li>
    <li>Power: {{selected_car.car_power}}</li>
    <li>Seats: {{selected_car.car_seating_capacity}}</li>
    <li>Standard Transmission: {{selected_car.car_standard_transmission}}</li>
    <li>Drive: {{selected_car.car_drive}}</li>
    <li>Wheel base: {{selected_car.car_wheel_base}}</li>
    
</ul>
  </div>
  <button class="button button1">RENT</button>
</div>
<!-- JavaScript for slideshow transission animation -->
<script>
var slideIndex = 0;
showSlides();

function showSlides() {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("dot");
    for (i = 0; i < slides.length; i++) {
       slides[i].style.display = "none"; 
    }
    slideIndex++;
    if (slideIndex > slides.length) {slideIndex = 1}    
    for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
    }
    setTimeout(showSlides, 2000); // Change image every 2 seconds
    slides[slideIndex-1].style.display = "block";
    dots[slideIndex-1].className += " active";
}
</script>
{% else %}
  <h1>Error! Car not found</h1>
{% endif %}
{% endblock content %}

ifb299_website/search/templates/search/home.html
{% extends "search/base.html" %}
{% load static %}
{% block content %}
<head>
<style>
.search-box {
	border:3px solid black;
	border-color: #000;
	width: 500px;
	background: none;
	margin-left: auto;
	margin-right: auto;
	display: block
}
.text-search {
	margin-left: 1em;
	font-style: bold;
	font-family: 'Arial';
}

.list-box {
	width: 32%;
	height: 400px;
	border: thin solid;
	border-color: #000000;
	color: #000000;
	float: left;
	margin-bottom: 1em;
	margin-right: 0.7em;
	padding: 10px;
}
</style>
</head>
<!--Creates search box, creates new lines after search text box and max price-->
<form action="{% url 'search:home' %}" method="GET">
	<div class="search-box">
		<p style="margin-left: 2em;"><h2 style="text-align: center;">Search for cars</h2></p>
		<p class="text-search">
			{% for field in form  %}
			{% if field.label == "Search" %}
					 <br><b>{{ field.label_tag }}</b> {{ field }}</br>
			{% elif field.label == "Min Price" %}
					 <br><b>{{ field.label_tag }}</b> {{ field }}
			{% elif field.label == "Max Price" %}
					 <b>{{ field.label_tag }}</b> {{ field }}</br>
			{% else %}
					<b>{{ field.label_tag }}</b>{{ field }}
			{% endif %}
			{% endfor %}
		</p>
  		<p style="margin-bottom: 5px; margin-left: 420px;"><input type ="submit" value="Submit"></p>
  	</div>
</form>
<!--If no results found, simply displays 'No results found'-->
{% if car_query_list %}
	<h3>Results Found</h3>

	<div style="background-color: #ffffff; margin-top: 1em;">
    {% for car in car_query_list %}
    <!-- Creates list item, will select image based on car make and model-->
    <table class="list-box">
	    <tbody>
	        <tr>
	            <td colspan="2" style="width: 99.6466%; background-color: #ffffff"><img src="/static/{{car.car_make}}/{{car.car_make}}_{{car.car_model}}.jpg" style="width: 240px; height: 170px; display: block; margin-left: auto; margin-right: auto" class="fr-fic fr-dib"></td>
	        </tr>
	        <tr>
	        	<!--Creates blue band with black text giving the cars make, model, series and year -->
	            <td colspan="2" style="width: 99.6466%; text-align: center; background-color: #5D8AA8;"><strong style="font-family: Arial;">{{car.car_make}} {{car.car_model}} {{car.car_series}} - {{car.car_series_year}}</strong></td>
	        </tr>
	        <tr>
	            <td style=""></td>
	            <td style="font-family: Times New Roman; text-align: right; color: #0054B4;"><font size = "5"><strong style=" margin-right: 3px;">${{car.car_price_new}}</strong></div></font></td>
	        <tr>
	            <td><font size = "4" style="font-family: Arial; margin-left: 1em;">Fuel_capacity: <strong>{{car.car_tank_capacity}}</strong></font></td>
	            <td><font size = "4" style="font-family: Arial; text-align: center;">Seats: <strong>{{car.car_seating_capacity}}</strong></font></td>
	        </tr>
	        <tr>
	            <td colspan="2" style="width: 49.8233%;background-color: none;"><div style="text-align: center;"><a class="button" href="{% url 'search:car_detail' car.car_id %}" style="color: #000000; display: block; margin-right: auto; margin-left: auto;"><span style="background-color: #5D8AA8; border: thin solid; border-color: #000000; display: inline-block; padding: 2px 8px; font-weight: bold; border-radius: 5px;">View details</span></a></div></td>

	        </tr>
	    </tbody>
	</table>
    {% endfor %}
    </div>
{% else %}
  <h3>No cars match your query<h3>
{% endif %}
{% endblock content%}

ifb299_website/search/templates/search/locations_old.html
{% extends "search/base.html" %}
{% block content %}

{% endblock content%}

ifb299_website/search/templates/search/search.html
{% extends "search/base.html" %}
{% block content %}

{% endblock content%}

ifb299_website/search/templates/search/test.html
{% extends "search/base.html" %}
{% load static %}
{% block content %}
<form action="{% url 'search:home' %}" method="GET">
  <div style="border:1px solid black; border-color: #000; width: 500px; margin-left: auto; margin-right: auto; display: block ">
    <p style="margin-left: 1em;"><h2 style="text-align: center;">Search for cars</h2></p>
      <p style="margin-left: 1em;"> <strong>{{ form }}</strong></p>
      <p style="margin-bottom: 5px; margin-left: 420px;"><input type ="submit" value="Submit"></p>
    </div>
</form>
{% if car_query_list %}
  <h3>Results Found</h3>
    {% for car in car_query_list %}
      <table border="1" style="width: 100%; border-collapse: collapse; border-color: #8b8989; background: #f5f5f5">
      <tbody>
        <tr style="height: 20%; ">
          <td style="width: 13%; border-color: #f5f5f5; height: 100%;" rowspan="2"><img src="https://htmlg.com/images/demo-image.jpg" alt="" width="100" height="100" style="display: block; margin-left: auto; margin-right: auto;" /></td>
          <td colspan="3" class="center-vertical">
            <p><strong><span style="font-size: large; font-family: Arial; ">{{car.car_make}} {{car.car_model}} {{car.car_series}} - {{car.car_series_year}}</span></strong></p>
          </td>
        </tr>
        <tr style="height: 80%;">
          <td style="width: 33%; border-color: #f5f5f5; text-align: left; vertical-align: top; height: 100%;">
            <p font="" size="3">Seats: {{car.car_seating_capacity}}</p>
            <p>Fuel Capacity: {{car.car_tank_capacity}}</p>
          </td>
          <td style="width: 17%; border-color: #f5f5f5; text-align: left; vertical-align: top; height: 100%;">
            <p>Price(New): ${{car.car_price_new}}</p>
          </td>
          <td style="width: 15%; border-color: #f5f5f5; text-align: center; vertical-align: top; height: 100%;">
            <p>&nbsp;</p>
            <p><a href="{% url 'search:car_detail' car.car_id %}" class="button" style="color: #000000;"><span style="background-color: #ffffff; border: thin solid; border-color: #000000; display: inline-block; padding: 2px 8px; font-weight: bold; border-radius: 5px;">View details</span></a></p>
          </td>
        </tr>
      </tbody>
    </table>
    <p></p>
    {% endfor %}
{% else %}
  <h3>No cars match your query<h3>
{% endif %}
{% endblock content%}